# Two services: backend API on 5000, frontend (nginx) on 80

services:
  backend:

    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://13.60.19.245:5001/api
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
